ClientWebApp/Models/LibraryItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.ComponentModel;

namespace ClientWebApp.Models
{
    //public enum LibraryItemType : byte
    //{
    //    [Description("DVD")]
    //    DVD = 1,
    //    [Description("CD")]
    //    CD = 2,
    //    [Description("Book")]
    //    Book = 3
    //};

    public class LibraryItem
    {
        public int Id { get; set; }
        public Author Author { get; set; }
        //public LibraryItemType ItemType { get; set; }
        public int ItemType { get; set; }
        public string Cover { get; set; }
        public DateTime IssueYear { get; set; }
        public string Title { get; set; }


    }

    //public enum LibraryItemType { DVD, CD, Book };

    //public class LibraryItem
    //{
    //    public int Id { get; set; }

    //    public virtual Author Author { get; set; }

    //    public LibraryItemType ItemType { get; set; }

    //    public string Cover { get; set; }

    //    public DateTime IssueYear { get; set; }

    //    [Required]
    //    public string Title { get; set; }


    //}
}

ClientWebApp/Models/LibraryItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;


namespace ClientWebApp.Models
{
    //public class LibraryItemViewModel
    //{
        //public enum LibraryItemType { DVD, CD, Book };

        //public class LibraryItem
        //{
        //    public int Id { get; set; }

        //    public virtual Author Author { get; set; }

        //    public LibraryItemType ItemType { get; set; }

        //    public string Cover { get; set; }

        //    public DateTime IssueYear { get; set; }

        //    [Required]
        //    public string Title { get; set; }
        //}

        //public enum LibraryItemType : byte
        //{
        //    [Description("DVD")]
        //    DVD = 1,
        //    [Description("CD")]
        //    CD = 2,
        //    [Description("Book")]
        //    Book = 3
        //};

        public class LibraryItemViewModel
        {
            public int Id { get; set; }
            public Author Author { get; set; }
            //public LibraryItemType ItemType { get; set; }
            public int ItemType { get; set; }
            public string Cover { get; set; }
            public DateTimeOffset IssueYear { get; set; }
            public string Title { get; set; }
        }
    //}
}

ClientWebApp/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AuthDatabase.Entities;
using ClientWebApp.Models;
using ClientWebApp.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ClientWebApp.Controllers
{
    public class AuthorItemController : Controller
    {
        private readonly IAuthorService _authorService;
        private readonly UserManager<AppUser> _userManager;

        public AuthorItemController(IAuthorService authorService, UserManager<AppUser> userManager)
        {
            _authorService = authorService;
            _userManager = userManager;
        }

        public IActionResult EnterAuthor()
        {
            var model = new Author();
            return View(model);
        }

        public async Task<IActionResult> SaveAuthor(Author newAuthor)
        {

            //int successfullTran = await _libraryItemService.AddLibraryItem(newItem);
            var successfullTran = await _authorService.AddAuthor(newAuthor);
            //if (successfullTran > 0)
            //{
            //    return BadRequest("Could not add item.");
            //}

            return RedirectToAction("EnterData", "LibraryItem");
        }
    }
}

ClientWebApp/Controllers/LibraryItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ClientWebApp.Client;
using ClientWebApp.Services;
using ClientWebApp.Models;
using AutoMapper;
using AuthDatabase.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ClientWebApp.Controllers
{
    public class LibraryItemController : Controller
    {
        private readonly ILibraryItemService _libraryItemService;
        private readonly IAuthorService _authorService;
        private readonly UserManager<AppUser> _userManager;


        public LibraryItemController(ILibraryItemService libraryItemService, IAuthorService authorService, UserManager<AppUser> userManager)
        {
            _libraryItemService = libraryItemService;
            _authorService = authorService;
            _userManager = userManager;
        }


        public async Task<IActionResult> LibraryItemsList(string searchTitle, string searchAuthorFirstName, string searchAuthorLastName, string searchItemType)
        {
            LibraryItemViewModel[] libraryItemsList = await _libraryItemService.GetAll();

            var items = from m in libraryItemsList
                        select m;

            if (!String.IsNullOrEmpty(searchTitle))
            {
                items = items.Where(s => s.Title.ToLower().Contains(searchTitle.ToLower()));
            }

            if (!String.IsNullOrEmpty(searchAuthorFirstName))
            {
                items = items.Where(s => s.Author.FirstName.ToLower().Contains(searchAuthorFirstName.ToLower()));
            }

            if (!String.IsNullOrEmpty(searchAuthorLastName))
            {
                items = items.Where(s => s.Author.LastName.ToLower().Contains(searchAuthorLastName.ToLower()));
            }

            var model = new LibraryViewModel()
            {
                Items = items.ToArray()
            };

            return View(model);
        }

        public async Task<IActionResult> EnterData()
        {
            LibraryItemViewModel[] libraryItemsList = await _libraryItemService.GetAll();
            var model = new LibraryItemViewModel();
            Author[] listaAutorow = await _authorService.GetAuthors(); 

            var authors = listaAutorow.Select(a => new SelectListItem
            {
                Text = a.LastName.ToString() + ' ' + a.FirstName.ToString(),
                Value = a.Id.ToString()
            });

            ViewBag.AuthorsViewBag = new SelectList(authors, "Value", "Text");
            return View(model);
        }
        private int _Id;
        public async Task<IActionResult> GetOneItem(int id)
        {
            _Id = id;
            LibraryItemViewModel libraryItemsList = await _libraryItemService.GetOne(_Id);

            return View(libraryItemsList);
        }



        [HttpPost]
        public async Task<IActionResult> SaveLibraryItem(LibraryItemViewModel newItem)
        {
            ClientWebApp.Client.FileResponse successfullTran;
            if (ModelState.IsValid)
            {
                successfullTran = await _libraryItemService.AddLibraryItem(newItem);
                return RedirectToAction("LibraryItemsList");
            }
            else
            {
                return BadRequest("Nie można dodać elementu, wszystkie pola muszą być uzupełnione.");
            }
        }
    }
}

ClientWebApp/Views/LibraryItem/EnterData.cshtml
@model LibraryItemViewModel;

@{
    ViewData["Title"] = "Wrowadź dane";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Dodaj element do biblioteki</title>

</head>
<body>

    <form asp-action="SaveLibraryItem" method="post">
        <fieldset>
            <legend>Informacje</legend>
            <div class="form-group">
                <label for="Title">Tytuł:</label>
                <input type="text" class="form-control" name="Title" placeholder="Tytuł" value="@Model.Title" />
            </div>

            <div class="form-group">
                <label for="Author">Imię autora:</label><br />
                @Html.DropDownListFor(m => m.Author.Id, new SelectList((IEnumerable<SelectListItem>)ViewBag.AuthorsViewBag, "Value", "Text"))
            </div>

            <div class="form-group">
                <label for="IssueYear">Data wydania</label>
                <input type="date" class="form-control" name="IssueYear" placeholder="Rok" value="@Model.IssueYear" />
            </div>

            <p><input type="submit" class="btn btn-primary" name="buttonSubmit" value="Dodaj Element" /></p>

        </fieldset>
    </form>
    <h2>Wprowadzanie autorów</h2>
    <ol>
        <li>

            <a asp-controller="AuthorItem"
               asp-action="EnterAuthor">Wprowadzanie autorów</a>

        </li>
    </ol>
</body>
</html>

ClientWebApp/Views/LibraryItem/GetOneItem.cshtml
@model LibraryItemViewModel;

@{
    ViewData["Title"] = "Wprowadzona pozycja";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Element w bibliotece</title>
</head>
<body>
    <form asp-action="SaveLibraryItem" method="post">
        <fieldset>
            <legend>Informacje</legend>
            <div class="form-group">
                <label for="Title">Tytuł:</label><br />
                <label>@Model.Title</label>
            </div>

            <div class="form-group">
                <label for="Author">Imię autora:</label><br />
                <label>@Model.Author.FirstName @Model.Author.LastName</label>
            </div>

            <div class="form-group">
                <label for="IssueYear">Data wydania:</label><br />
                <label>@Model.IssueYear.Date.ToString("yyyy/MM/dd")</label>
            </div>
        </fieldset>
    </form>
</body>
</html>

ClientWebApp/Views/LibraryItem/Index.cshtml
@model LibraryViewModel;
@*@using Humanizer;*@
@{
    ViewData["Title"] = "Library Items";
}

<div class="text-center">
    <h1 class="display-4">Library Items!</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="panel panel-default todo-panel">
    <div class="panel-heading">@ViewData["Title"]</div>

    <table class="table table-hover">
        <thead>
            <tr>
                <td>&#x2714;</td>
                <td>Item</td>
                <td>Due</td>
            </tr>
        </thead>

        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @*<form asp-action="MarkDone" method="POST">
                            <input type="checkbox" class="done-checkbox" onchange="this.form.submit()">
                            <input type="hidden" name="id" value="@item.Id">
                        </form>*@
                </td>
                <td>@item.Author.FirstName @item.Author.LastName</td>
                <td>@item.Title</td>
            </tr>
        }
    </table>

    @*<div class="panel-footer add-item-form">

        @await Html.PartialAsync("_AddItemPartial", new LibraryItemViewModel())
    </div>*@

</div>

ClientWebApp/Views/LibraryItem/LibraryItemsList.cshtml
@model LibraryViewModel;
@{
    ViewData["Title"] = "Lista Elementów";
}

<div class="text-center">
    <h1 class="display-4">Zawartość Biblioteki</h1>
</div>

<form asp-controller="LibraryItem" asp-action="LibraryItemsList" method="get">
    <p>

        Tytuł: <input type="text" name="SearchTitle">
        Imię Autora: <input type="text" name="SearchAuthorFirstName">
        Nazwisko Autora: <input type="text" name="SearchAuthorLastName">
        <input type="submit" value="Filtr" />
    </p>
</form>

<div class="panel panel-default todo-panel">
    

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>&#x2714;</th>
                <th>Tytuł</th>
                <th>Imię i Nazwisko Autora</th>
                <th>Rok Wydania</th>
            </tr>
        </thead>

        @foreach (var item in Model.Items)
        {
        <tr onclick="location.href = '@(Url.Action("GetOneItem", "LibraryItem", new { id = item.Id}))'">
            <td>&#x25BB;</td>
            <td>@item.Title</td>
            <td>@item.Author.FirstName @item.Author.LastName</td>
            <td>@item.IssueYear.Year</td>
        </tr>
        }
    </table>
</div>

ClientWebApp/Views/LibraryItem/ViewData.cshtml
@model LibraryItemViewModel;

@{
    ViewData["Title"] = "Wprowadzona pozycja";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Element w bibliotece</title>
</head>
<body>
    <form asp-action="SaveLibraryItem" method="post">
        <fieldset>
            <legend>Informacje</legend>
            <div class="form-group">
                <label for="Title">Tytuł:</label><br />
                <label>@Model.Title</label>
            </div>

            <div class="form-group">
                <label for="Author">Autor:</label><br />
                <label>@Model.Author.FirstName - @Model.Author.LastName</label>
                @*@Html.DropDownListFor(m => m.Author.Id, new SelectList((IEnumerable<SelectListItem>)ViewBag.AuthorsViewBag, "Value", "Text"))*@
            </div>

            <div class="form-group">
                <label for="IssueYear">Data wydania:</label><br />
                <label>@Model.IssueYear</label>
                @*<input type="date" class="form-control" name="IssueYear" placeholder="Rok" value="@Model.IssueYear" />*@
            </div>

            @*<div class="form-group">
                <label for="ItemType">Nośnik:</label>
                @Html.DropDownListFor(m => m.ItemType, new SelectList((IEnumerable<SelectListItem>)Html.GetEnumSelectList(typeof(int)), "Value", "Text"))
            </div>*@

            @*<div class="form-group">
                    <label for="Cover">Okładka:</label>
                    <input type="text" class="form-control" name="Cover" placeholder="Okładka" />
                </div>*@

            <p><input type="submit" class="btn btn-primary" name="buttonSubmit" value="Dodaj Element" /></p>

        </fieldset>
    </form>
    <h2>Wprowadzanie autorów</h2>
    <ol>
        <li>

            <a asp-controller="AuthorItem"
               asp-action="EnterAuthor">Wprowadzanie autorów</a>

        </li>
    </ol>
</body>
</html>